### ISSUE TITLE
Populate must accept an object

### ISSUE THREAD

**Issue by dmitrybelyakov** [Stun3R/strapi-sdk-js#108]
## Bug report

`populate` query parameter only accepts strings and lists, passing an object is not allowed.

### Describe the bug

I am trying to deeply populate a dynamic zone having unknown set of components who's field names are unknown upfront. Strapi seems to support this as per example in their documentation: [Deeply populate a dynamic zone with 2 components](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#deeply-populate-a-dynamic-zone-with-2-components):

```javascript
const result = await this.$strapi.find('pages', {
  populate: {
    sections: {
      populate: '*'
    },
  },
});
```

`strapi-sdk-js` does not allow to define `populate` parameter as an object as per Strapi documentation.

### Steps to reproduce the behavior

1. Go to the documentation link posted above
2. Copy the query
3. Try using `populate` parameter with `strapi-sdk-js`
4. See error: only `string | string[]` is allowed

### Expected behavior

The `populate` object should be accepted and correctly encoded into a query string, looking something like this:

```
/api/pages?populate[sections][populate]=%2A
```

**Comment by nextrapi** [comment]
I believe only this line 
https://github.com/Stun3R/strapi-sdk-js/blob/43b71d1d94daca353d6a0ba31414c033e0b1a0f1/src/lib/types.ts#L556
needs to be changed to include objects.

**Comment by Stun3R** [comment]
> ## Bug report
> `populate` query parameter only accepts strings and lists, passing an object is not allowed.
> 
> ### Describe the bug
> I am trying to deeply populate a dynamic zone having unknown set of components who's field names are unknown upfront. Strapi seems to support this as per example in their documentation: [Deeply populate a dynamic zone with 2 components](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/populating-fields.html#deeply-populate-a-dynamic-zone-with-2-components):
> 
> ```js
> const result = await this.$strapi.find('pages', {
>   populate: {
>     sections: {
>       populate: '*'
>     },
>   },
> });
> ```
> 
> A clear and concise description of what the bug is.
> 
> `strapi-sdk-js` does not allow to define `populate` parameter as an object as per Strapi documentation.
> 
> ### Steps to reproduce the behavior
> 1. Go to the documentation link posted above
> 2. Copy the query
> 3. Try using `populate` parameter with `strapi-sdk-js`
> 4. See error: only `string | string[]` is allowed
> 
> ### Expected behavior
> The `populate` object should be accepted and correctly encoded into a query string, looking something like this:
> 
> ```
> /api/pages?populate[sections][populate]=%2A
> ```

Hi @nextrapi 👋🏻

Thanks for this issue! I'll look into it & do some testing so I could fix it as soon as possible (It should be released tomorrow) 🙌🏻
