### ISSUE TITLE
removeToken on subdomain

### ISSUE THREAD

**Issue by cossssmin** [Stun3R/strapi-sdk-js#132]
Hey, thanks for your work on the library! :)

I'm using `strapi-sdk-js` like this in Nuxt 2:

```js
import Strapi from 'strapi-sdk-js'

export default ({$config}, inject) => {
  const strapi = new Strapi({
    url: $config.strapiBase,
    store: {
      cookieOptions: {
        path: '/',
        expires: 90,
        domain: example.com,
      },
    }
  })

  inject('strapi', strapi)
}
```

My app is located at `my.example.com`.

When calling `strapi.logout()` (or `strapi.removeToken()`), it doesn't remove the `strapi_jwt` cookie (because it's on a different domain?), so you can go back and still browse the app as if you were logged in, because the token is still in storage.

This is also a problem if you try to log in right after logging out - trying to log in with a valid token present in storage will not work.

**Comment by Stun3R** [comment]
Hey 👋🏼 Sorry for late reply, I've had some changes in my life that have taken me away from this package for a while.

Do you still have this issue?

**Comment by cossssmin** [comment]
Hey there, no worries, totally understand (and hope you’re better now). We’ve long closed the project so we don’t have the issue anymore, we also no longer use Nuxt 2 - sorry I forgot about it. 

I’ll go ahead and close it 👍
