### ISSUE TITLE
strapi.register(): strapi_jwt is undefined

### ISSUE THREAD

**Issue by cossssmin** [Stun3R/strapi-sdk-js#133]
I'm registering a user in Nuxt like so:

```js
await this.$strapi.register({
  email: this.email,
  username: this.username,
  password: this.password,
})
```

When I check the Application tab in the Dev Tools to see the `strapi_jwt` cookie that should have been set, it is `undefined`:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/1656595/158477545-fb3bcd24-7fdd-4d6d-bf5c-ae9af6b13bcf.png">

This makes it impossible to make additional requests, because there is no token set. In my case, I need to set the `firstName` and `lastName` of the created user after registration, like advised in #128.

**Comment by Stun3R** [comment]
Hey 👋🏼 Sorry for late reply, I've had some changes in my life that have taken me away from this package for a while.

Do you still have this issue?

**Comment by cossssmin** [comment]
No need, closing as per the other issue 👍
