### ISSUE TITLE
Upload & Bulk Upload

### ISSUE THREAD

**Issue by aldycavalera** [Stun3R/strapi-sdk-js#134]
### Summary
I've created new feature upload & multiple file upload, can i contribute ?

### Why is it needed?
It's helpful when we have upload feature

**Comment by Stun3R** [comment]
Hi @aldycavalera
Can you provide more informations about what you plan to do like code snippet, examples? ☺️

**Comment by aldycavalera** [comment]
Okay, so strapi had upload feature, it seems like strapi-sdk-js doesn't have the features that allow user to upload their files yet. So i made a simple function to achieve that, i created these two : 

### `upload(file, callback)`
to upload single file
```ts
const file = new File(['foo'], 'bar')
await strapi.upload(file, (res) => {
    console.log(res)
})
```

### `bulkUpload(files, callback)`
Upload multiple files at once
```ts
const files = [new File(['foos'], 'bars'), new File(['bars'], 'foos')]
await strapi.bulkUpload(files, (res) => {
    console.log(res)
})
```

it would be awesome if you allow me to create a pr, and submit a review :)

**Comment by huy-lv** [comment]
hey, what is the current status of this issue

**Comment by Stun3R** [comment]
For now there is no plan to add an `upload` method set but will look into it to check if it's relatively needed

**Comment by huy-lv** [comment]
@Stun3R  can I make a PR for this
