### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by JE1999** [Stun3R/strapi-sdk-js#139]
### Describe the bug

import error, says: `Object(...) is not a function` when I try to import strapi sdk in reactjs.

_I'm using yarn, I don't know if that affects anything but i have also tried with npm_

### Steps to reproduce the behavior

I only do the import of strapi and when I save I already have the error present, I have also added the documentation options but the error still persists

![image](https://user-images.githubusercontent.com/45927529/170914425-415d7ad7-e408-4cce-ad07-ddae047a765a.png)

### Screenshots

![image](https://user-images.githubusercontent.com/45927529/170913780-c198144b-823e-4395-954d-7178e7257431.png)

### Code snippets

![image](https://user-images.githubusercontent.com/45927529/170914099-c1a4b72f-606f-49ca-81d6-3233fb6f88a1.png)

### System

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: 4.1.8
- Strapi SDK version: 2.2.0
- Operating system: windows 10 home

**Comment by Stun3R** [comment]
Hey 👋🏼 Sorry for late reply, I've had some changes in my life that have taken me away from this package for a while.

Do you still have this issue?
