### ISSUE TITLE
CI/CD Broken

### ISSUE THREAD

**Issue by AnnikenYT** [Stun3R/strapi-sdk-js#144]
### Describe the bug

Netlify Build Image is outdated, and therefor produces wrong CI Status.

### Steps to reproduce the behavior

1. Commit to repository
2. Open Netlify build log

### Expected behavior

Build happens or fails.

### Screenshots

[Netlify Log](https://app.netlify.com/sites/strapi-sdk-js/deploys/63d864e879720f000804bb35)

### Code snippets

N/A

### System

N/A

### Additional context

N/A

**Comment by LeBovin** [comment]
I was looking to make a PR but I'm worrying as there is not much activity on this repository.
Is it still maintained? @Stun3R

**Comment by Stun3R** [comment]
Hey 👋🏼 It is still maintained but don't have many time to check as I do it in my free time and it's missing coz of work :D Will have a look during this week

**Comment by LeBovin** [comment]
Thank you for your answer!
Are you looking for help to maintain the project? I might give a hand if needed

**Comment by Stun3R** [comment]
Sorry for the late fix but now I should be more active! It's fixed
