### ISSUE TITLE
SyntaxError: The requested module 'ufo' does not provide an export named 'default'

### ISSUE THREAD

**Issue by huy-lv** [Stun3R/strapi-sdk-js#182]
### Describe the bug

Error when I use lib version ^2.3.1

### System

- Node.js version: 16.20.1
- NPM version: 9.6.4
- Strapi version: 4.12.5
- Strapi SDK version: 
- Operating system: Mac

**Comment by Stun3R** [comment]
Hey 👋🏼 Thanks for this issue.

A PR that's gonna fix this is in progress: #181

**Comment by Stun3R** [comment]
I just merged a fix and will release soon. It might break your app if you are using old webpack. To to better understand it check this comment: https://github.com/Stun3R/strapi-sdk-js/pull/181#issuecomment-1686836832
